# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://ankur3107.github.io/knowledge-extractor/"

git_url = "https://github.com/ankur3107/knowledge-extractor/tree/master/"

def custom_doc_links(name): return None
