# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"BartKeywordGenerator": "00_model_based_keyword_generation.ipynb",
         "ExtractiveKeywordGenerator": "00_model_based_keyword_generation.ipynb",
         "AbstractiveKeywordGenerator": "00_model_based_keyword_generation.ipynb"}

modules = ["keyword_generators.py"]

doc_url = "https://ankur3107.github.io/knowledge_extractor/"

git_url = "https://github.com/ankur3107/knowledge_extractor/tree/master/"

def custom_doc_links(name): return None
